[project]
name = "mealie-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.0",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
    "textual>=6.2.1",
]
